### ISSUE TITLE
Drag Drop element

### ISSUE THREAD

**Issue by FrankySnow** [pankajparashar/canidev.tools#11] opened 2022-06-04 23:01 UTC
**Browser:**
Firefox

**Platform:**
Windows

**Notes:**
Drag & dropping DOM nodes is also possible in Firefox, exactly like in Chrome

**Media:**
n/a

**References:**
n/a

**Comment by pankajparashar** [comment] 2022-06-05 05:21
Duplicate of #3. 
https://www.canidev.tools/?id=drag-drop-element&browser=Firefox

**Closed by pankajparashar** 2022-06-05 05:21 UTC

**Comment by FrankySnow** [comment] 2022-06-05 13:03
Sorry for the duplicate, and thank you for your work !
